apiVersion: v1
kind: Service
metadata:
  name: autodeploy
  namespace: namespace-workflow-1716651034438
spec:
  type: LoadBalancer
  selector:
    app: autodeploy
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000